export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SET_TOTAL = "SET_TOTAL";
export const SET_FETCH_STATE = "SET_FETCH_STATE";
export const SET_LIMIT = "SET_LIMIT";
export const SET_OFFSET = "SET_OFFSET";
export const SET_FILTER = "SET_FILTER";

// Category fetch action types
export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_ERROR = "FETCH_CATEGORIES_ERROR";

// Products fetch action types
export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

// Infinite scroll action types
export const LOAD_MORE_PRODUCTS_START = "LOAD_MORE_PRODUCTS_START";
export const LOAD_MORE_PRODUCTS_SUCCESS = "LOAD_MORE_PRODUCTS_SUCCESS";
export const LOAD_MORE_PRODUCTS_ERROR = "LOAD_MORE_PRODUCTS_ERROR";
export const RESET_PRODUCTS = "RESET_PRODUCTS";
export const SET_HAS_MORE = "SET_HAS_MORE";

// Product detail action types
export const FETCH_PRODUCT_DETAIL_START = "FETCH_PRODUCT_DETAIL_START";
export const FETCH_PRODUCT_DETAIL_SUCCESS = "FETCH_PRODUCT_DETAIL_SUCCESS";
export const FETCH_PRODUCT_DETAIL_ERROR = "FETCH_PRODUCT_DETAIL_ERROR";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
